api_platform:
    swagger:
        api_keys:
             apiKey:
                name: Authorization
                type: header
        versions: [3]
    
    title: 'Museo API'

    description: 'API Publique de MUSEO'

    version: '0.1'
    
    enable_swagger: true

    # Enable Swagger ui.
    enable_swagger_ui: true

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    patch_formats:
        json: ['application/merge-patch+json']

    doctrine:
        # To enable or disable Doctrine ORM support.
        enabled: true

    doctrine_mongodb_odm:
        # To enable or disable Doctrine MongoDB ODM support.
        enabled: false
    
    eager_loading:

        # To enable or disable eager loading.
        enabled: true

        # Fetch only partial data according to serialization groups.
        # If enabled, Doctrine ORM entities will not work as expected if any of the other fields are used.
        fetch_partial: true

        # Max number of joined relations before EagerLoading throws a RuntimeException.
        max_joins: 30

        # Force join on every relation.
        # If disabled, it will only join relations having the EAGER fetch mode.
        force_eager: false