api_platform:
    swagger:
        api_keys:
             apiKey:
                name: Authorization
                type: header
        versions: [3]
    
    title: 'Museo API'
    description: 'API Publique de MUSEO'
    version: '0.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
