easy_admin:
   entities:
       # List the entity class name you want to manage
       - App\Entity\Monument
       - App\Entity\Category
       - App\Entity\Period
       - App\Entity\Region
       - App\Entity\Target
    #    - App\Entity\User
