vich_uploader:
    db_driver: orm

    mappings:
       media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/assets/img/media'
            namer: Vich\UploaderBundle\Naming\OrignameNamer