vich_uploader:
    db_driver: orm
    twig: true
    form: true
    storage: file_system

    mappings:
        monument_image:
            uri_prefix: /assets/img/upload/monuments
            upload_destination: '%kernel.project_dir%/public/assets/img/upload/monuments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
