-- Doctrine Migration File Generated on 2020-03-19 17:39:22

-- Version 20200313081407
ALTER TABLE monument ADD image VARCHAR(255) DEFAULT NULL;
INSERT INTO migration_versions (version, executed_at) VALUES ('20200313081407', CURRENT_TIMESTAMP);

-- Version 20200316143407
ALTER TABLE monument ADD is_active TINYINT(1) DEFAULT NULL;
INSERT INTO migration_versions (version, executed_at) VALUES ('20200316143407', CURRENT_TIMESTAMP);

-- Version 20200317114256
ALTER TABLE user ADD activation_token VARCHAR(50) DEFAULT NULL;
INSERT INTO migration_versions (version, executed_at) VALUES ('20200317114256', CURRENT_TIMESTAMP);

-- Version 20200319101703
ALTER TABLE monument DROP FOREIGN KEY FK_7BB882833DA5256D;
DROP TABLE media_object;
DROP TABLE monument_period;
DROP INDEX IDX_7BB882833DA5256D ON monument;
ALTER TABLE monument ADD period_id INT DEFAULT NULL, ADD image_name VARCHAR(255) NOT NULL, ADD image_size INT NOT NULL, DROP image_id, DROP category_id, DROP image;
ALTER TABLE monument ADD CONSTRAINT FK_7BB88283EC8B7ADE FOREIGN KEY (period_id) REFERENCES period (id);
CREATE INDEX IDX_7BB88283EC8B7ADE ON monument (period_id);
INSERT INTO migration_versions (version, executed_at) VALUES ('20200319101703', CURRENT_TIMESTAMP);

-- Version 20200319163849
CREATE TABLE region (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, zipcode INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, firstname VARCHAR(255) DEFAULT NULL, lastname VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, is_active TINYINT(1) NOT NULL, activation_token VARCHAR(50) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE period (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE target (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE monument (id INT AUTO_INCREMENT NOT NULL, region_id INT NOT NULL, target_id INT DEFAULT NULL, period_id INT DEFAULT NULL, image_name VARCHAR(255) DEFAULT NULL, image_size INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, address VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, available TINYINT(1) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, INDEX IDX_7BB8828398260155 (region_id), INDEX IDX_7BB88283158E0B66 (target_id), INDEX IDX_7BB88283EC8B7ADE (period_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE monument_category (monument_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_14351E49493DA1E5 (monument_id), INDEX IDX_14351E4912469DE2 (category_id), PRIMARY KEY(monument_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
CREATE TABLE refresh_tokens (id INT AUTO_INCREMENT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid DATETIME NOT NULL, UNIQUE INDEX UNIQ_9BACE7E1C74F2195 (refresh_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB;
ALTER TABLE monument ADD CONSTRAINT FK_7BB8828398260155 FOREIGN KEY (region_id) REFERENCES region (id);
ALTER TABLE monument ADD CONSTRAINT FK_7BB88283158E0B66 FOREIGN KEY (target_id) REFERENCES target (id);
ALTER TABLE monument ADD CONSTRAINT FK_7BB88283EC8B7ADE FOREIGN KEY (period_id) REFERENCES period (id);
ALTER TABLE monument_category ADD CONSTRAINT FK_14351E49493DA1E5 FOREIGN KEY (monument_id) REFERENCES monument (id) ON DELETE CASCADE;
ALTER TABLE monument_category ADD CONSTRAINT FK_14351E4912469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE;
INSERT INTO migration_versions (version, executed_at) VALUES ('20200319163849', CURRENT_TIMESTAMP);
